"""Constants used in NIMO-GUI"""

from typing import Literal, Optional, TypeAlias


##################### Basic parameters #####################

MAX_OBJECTIVES: int = 4
MAX_CYCLES: int = 100
MAX_PROPOSALS: int = 60
DEFAULT_PROPOSALS: int = 10

###################### AI algorithms #######################

AI_ALGORITHM_RE: Literal['RE'] = 'RE'
AI_ALGORITHM_PHYSBO: Literal['PHYSBO'] = 'PHYSBO'
AI_ALGORITHM_PDC: Literal['PDC'] = 'PDC'
AI_ALGORITHM_BLOX: Literal['BLOX'] = 'BLOX'
AI_ALGORITHM_PTR: Literal['PTR'] = 'PTR'
AI_ALGORITHM_SLESA: Literal['SLESA'] = 'SLESA'
AI_ALGORITHM_ORIGINAL: Literal['Original'] = 'Original'

AI_ALGORITHMS: list[str] = [
    AI_ALGORITHM_RE,
    AI_ALGORITHM_PHYSBO,
    AI_ALGORITHM_PDC,
    AI_ALGORITHM_BLOX,
    AI_ALGORITHM_PTR,
    AI_ALGORITHM_SLESA,
    AI_ALGORITHM_ORIGINAL
]

DEFAULT_AI_ALGORITHM: str = AI_ALGORITHM_RE

################### AI algorithm options ###################

# RE
DEFAULT_OPTION_RE_RE_SEED: Optional[int] = None

# PHYSBO
OPTION_PHYSBO_SCORE_TS: Literal['TS'] = 'TS'
OPTION_PHYSBO_SCORE_EI: Literal['EI'] = 'EI'
OPTION_PHYSBO_SCORE_PI: Literal['PI'] = 'PI'
OPTION_PHYSBO_SCORE_EHVI: Literal['EHVI'] = 'EHVI'
OPTION_PHYSBO_SCORE_HVPI: Literal['HVPI'] = 'HVPI'

OPTIONS_PHYSBO_SCORE_SINGLE: list[str] = [
    OPTION_PHYSBO_SCORE_TS,
    OPTION_PHYSBO_SCORE_EI,
    OPTION_PHYSBO_SCORE_PI
]

OPTIONS_PHYSBO_SCORE_MULTI: list[str] = [
    OPTION_PHYSBO_SCORE_TS,
    OPTION_PHYSBO_SCORE_EHVI,
    OPTION_PHYSBO_SCORE_HVPI
]

DEFAULT_OPTION_PHYSBO_SCORE_SINGLE: str = OPTION_PHYSBO_SCORE_TS
DEFAULT_OPTION_PHYSBO_ARD_SINGLE: bool = False
DEFAULT_OPTION_PHYSBO_OUTPUT_RES_SINGLE: bool = False
DEFAULT_OPTION_PHYSBO_SCORE_MULTI: str = OPTION_PHYSBO_SCORE_TS
DEFAULT_OPTION_PHYSBO_ARD_MULTI: bool = False
DEFAULT_OPTION_PHYSBO_OUTPUT_RES_MULTI: bool = False

# BLOX
DEFAULT_OPTION_BLOX_OUTPUT_RES: bool = False

# PDC
OPTION_PDC_ESTIMATION_LP: Literal['LP'] = 'LP'
OPTION_PDC_ESTIMATION_LS: Literal['LS'] = 'LS'

OPTIONS_PDC_ESTIMATION: list[str] = [
    OPTION_PDC_ESTIMATION_LP,
    OPTION_PDC_ESTIMATION_LS
]

OPTION_PDC_SAMPLING_LC: Literal['LC'] = 'LC'
OPTION_PDC_SAMPLING_MS: Literal['MS'] = 'MS'
OPTION_PDC_SAMPLING_EA: Literal['EA'] = 'EA'

OPTIONS_PDC_SAMPLING: list[str] = [
    OPTION_PDC_SAMPLING_LC,
    OPTION_PDC_SAMPLING_MS,
    OPTION_PDC_SAMPLING_EA
]

DEFAULT_OPTION_PDC_ESTIMATION: str = OPTION_PDC_ESTIMATION_LP
DEFAULT_OPTION_PDC_SAMPLING: str = OPTION_PDC_SAMPLING_LC
DEFAULT_OPTION_PDC_OUTPUT_RES: bool = False

# SLESA
DEFAULT_OPTION_SLESA_BETA_MAX: float = 0.0
DEFAULT_OPTION_SLESA_BETA_NUM: int = 0
DEFAULT_OPTION_SLESA_RE_SEED: Optional[int] = None
DEFAULT_OPTION_SLESA_OUTPUT_RES: bool = False

# PTR
DEFAULT_OPTION_PTR_OUTPUT_RES: bool = False

###################### Robot systems #######################

ROBOTIC_SYSTEM_STAN: Literal['STAN'] = 'STAN'
ROBOTIC_SYSTEM_NAREE: Literal['NAREE'] = 'NAREE'
ROBOTIC_SYSTEM_ORIGINAL: Literal['Original'] = 'Original'

ROBOT_SYSTEMS: list[str] = [
    ROBOTIC_SYSTEM_STAN,
    ROBOTIC_SYSTEM_NAREE,
    ROBOTIC_SYSTEM_ORIGINAL
]

DEFAULT_ROBOT_SYSTEM: str = ROBOTIC_SYSTEM_ORIGINAL

############################################################

WORKING_STATE_CONFIGURATION: Literal['configuration'] = 'configuration'
WORKING_STATE_RUN: Literal['run'] = 'run'
WORKING_STATE_SUSPENDING: Literal['suspending'] = 'suspending'
WORKING_STATE_SUSPENDED: Literal['suspended'] = 'suspended'

WorkingState: TypeAlias = Literal['configuration', 'run', 'suspending', 'suspended']

APP_STATE_KEY: str = 'nimo_gui_state'
